# .github/workflows/deploy.yml (Production Ready Version)

name: Deploy Python Functions to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('functions-python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv functions-python/venv
          source functions-python/venv/bin/activate
          pip install -r functions-python/requirements.txt
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IEMS_PLUS }}
          PROJECT_ID: iems-plus
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > ./service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json
          firebase deploy --only functions:python-ml --project ${PROJECT_ID} --non-interactive