# .github/workflows/deploy.yml

name: Deploy Python Functions to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          # This uses the secret you created in GitHub
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IEMS_PLUS }}
          PROJECT_ID: iems-plus
        run: |
          # Create the service account file from the secret
          echo "${FIREBASE_SERVICE_ACCOUNT}" > ./service-account.json

          # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable
          export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json
          
          # Deploy without the deprecated --token flag
          firebase deploy --only functions:python-ml --project ${PROJECT_ID} --non-interactive